# exception handling
try:
    x = 0
    num = 10
    res = num/x
    print(res)
except:
    print("arithmatic exception")

finally:
    print("love y")


